name: thử nghiệm đọc file README #Tên quy trình

on:  
    push:
      branch:["main"]
    jobs:
      thuc_hanh_doc_file:
        runs-on: ubuntu-latest
        
        steps:
          - name: Bước 1- Xin chào
           run: echo "hello world"  

          - name: Bước 2 - Tải code
           uses: action/checout@v6 #Robot tự động copy code vào máy ảo

          - name: Bước 3 - Đọc file
           run: cat README.md     #mở nội dung file README.md để xem
           
